### ISSUE TITLE
.zip support

### ISSUE THREAD

**Issue by PuppyLover101** [arfoll/unrarall#56]
Hi there, does this support *.zip files as well as *.rar? Considering there is 7ZIP support. Thanks! Looks like an awesome tool.

**Comment by arfoll** [comment]
Unfortunately no, 7zip support is because I was trying to optimise the speed, though with modern hardware this is all pretty pointless :)
Tbh if someone wants to fix all the regexps to find zip files they're more than welcome but maintaining such a bash script is already a complete mess, reality is it should move to a proper language at this point...
